name: "Terraform Deploy NGINX"
on:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  AWS_REGION: il-central-1
  TF_WORKING_DIR: .

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init -input=false

      - name: Terraform Plan
        id: tf-plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform plan -detailed-exitcode -out=tfplan.binary -input=false
          echo "plan_exit_code=$?" >> $GITHUB_OUTPUT

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: terraform-plan
          path: ${{ env.TF_WORKING_DIR }}/tfplan.binary

      - name: Terraform Apply
        if: steps.tf-plan.outputs.plan_exit_code == '2'
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -auto-approve -input=false tfplan.binary
        
      - name: Show Outputs
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform output
