name: docker image ci

on:
  push:
    paths:
      - Dockerfile
  workflow_dispatch: {}

env:
  DOCKERHUB_USERNAME: idanpersi
  IMAGE_AND_TAG: moveo-nginx:latest
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_AND_TAG }}
      
      - name: Build
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_AND_TAG }}
     
      - name: Inspect
        run: |
          docker image inspect ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_AND_TAG }}
