name: ci

on:
  push:
    paths:
      - Dockerfile
  workflow_dispatch: {}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: idanpersi/moveo-nginx:latest
      
      - name: Inspect
        run: |
          docker image inspect idanpersi/moveo-nginx:latest
